[package]
name = "example"
version = "0.1.0"
edition = "2021"

[dependencies]
rs-dagcuter = { path = "../" }
tokio = { version = "1.0", features = ["full"] }
async-trait = "0.1"
tokio-util = "0.7"
serde_json = "1.0"
chrono = "0.4"
